FROM tensorflow/tensorflow:latest-gpu-py3-jupyter

RUN pip install --upgrade pip
RUN pip install pandas \
    		tensorflow-hub \
		matplotlib \
    		seaborn \
		wordcloud \
		sentencepiece \
		sklearn
